kind: pipeline
type: docker
name: default

steps:
- name: BUILD s2i-nodejs-10-git-centos7
  image: getais/drone-plugin-s2i
  volumes:
    - name: docker-socket
      path: /var/run/docker.sock
  commands:
    - docker build -t s2i-nodejs-10-git-centos7 s2i-nodejs-10-git/

- name: BUILD s2i-nodered-base-centos7
  image: getais/drone-plugin-s2i
  volumes:
    - name: docker-socket
      path: /var/run/docker.sock
  commands:
    - s2i build s2i-nodered-base/ s2i-nodejs-10-git-centos7 s2i-nodered-base-centos7


- name: BUILD s2i-nodered-centos7
  image: getais/drone-plugin-s2i
  volumes:
    - name: docker-socket
      path: /var/run/docker.sock
  environment:
    DOCKER_USER:
      from_secret: DOCKER_USER
    DOCKER_TOKEN:
      from_secret: DOCKER_TOKEN
  commands:
    - docker build -t getais/s2i-nodered-centos7 -t getais/s2i-nodered-centos7:1.1 s2i-nodered/
    - docker login -u $DOCKER_USER -p $DOCKER_TOKEN
    - docker push getais/s2i-nodered-centos7
    - docker push getais/s2i-nodered-centos7:1.1


- name: BUILD nodered-example-app
  image: getais/drone-plugin-s2i
  volumes:
    - name: docker-socket
      path: /var/run/docker.sock
  commands:
    - s2i build example-app s2i-nodered-centos7 nodered-example-app



volumes:
  - name: docker-socket
    host:
      path: /var/run/docker.sock
