kind: pipeline
type: docker
name: default

steps:
- name: Install S2i
  image: alpine
  volumes:
    - name: docker-socket
      path: /var/run/docker.sock
  commands:
    - wget -O - https://github.com/openshift/source-to-image/releases/download/v1.2.0/source-to-image-v1.2.0-2a579ecd-linux-amd64.tar.gz | tar -xzvf -

- name: Build docker image via S2I
  image: alpine
  volumes:
    - name: docker-socket
      path: /var/run/docker.sock
  commands:
    - ./s2i build . centos/nodejs-10-centos7 nodered-base-centos7


volumes:
  - name: docker-socket
    host:
      path: /var/run/docker.sock

